services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
    image: spheronnetwork/genlayer-frontend:latest

  jsonrpc:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.backend
    image: spheronnetwork/genlayer-jsonrpc:latest

  webrequest:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.webrequest
    image: spheronnetwork/genlayer-webrequest:latest

  database-migration:
    build:
      context: .
      dockerfile: docker/Dockerfile.database-migration
    image: spheronnetwork/genlayer-database-migration:latest
