services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./examples:/app/src/assets/examples
    depends_on:
      - jsonrpc
    expose:
      - "${FRONTEND_PORT}"
  jsonrpc:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.backend
      target: debug
    environment:
      - FLASK_SERVER_PORT=${RPCPORT}
      # TODO: remove this in production
      - PYTHONUNBUFFERED=1
      - RPCDEBUGPORT=${RPCDEBUGPORT}
    ports:
      - "${RPCPORT}:${RPCPORT}"
      - "${RPCDEBUGPORT}:${RPCDEBUGPORT}"
    volumes:
      - ./.env:/app/.env
      - ./backend:/app/backend
    depends_on:
      - ollama
      - postgres
    expose:
      - "${RPCPORT}"

  webrequest:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.webrequest
    shm_size: 2gb
    volumes:
      - ./webrequest:/app/webrequest
    environment:
      - FLASK_SERVER_PORT=${WEBREQUESTPORT}
      # TODO: remove this in production
      - PYTHONUNBUFFERED=1
    expose:
      - "${WEBREQUESTPORT}"

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./.ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
  postgres:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.database
    ports:
      - "${DBPORT}:5432"
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    # If you want your db to persist in dev
    #volumes:
    #  - "./data/postgres:/var/lib/postgresql/data"
