version: '3'

services:

  jsonrpc:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.rpc
    environment:
      - FLASK_SERVER_PORT=${RPCPORT}
      # TODO: remove this in production
      - PYTHONUNBUFFERED=1
    ports:
      - "${RPCPORT}:${RPCPORT}"
    volumes:
      - ./rpc:/app/rpc
      - ./database:/app/database
      - ./consensus:/app/consensus
    depends_on:
      - ollama
      - postgres
      - genvm
  
  genvm:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.genvm
    environment:
      - FLASK_SERVER_PORT=${GENVMPORT}
      - DEBUG=${GENVMDEBUG}
      - PYTHONUNBUFFERED=${GENVMDEBUG}
    expose:
      - "${GENVMPORT}"
    volumes:
      - ./genvm:/app/genvm

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./.ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always

  postgres:
    image: postgres:12.17
    restart: always
    # TODO: Remove in production
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    # If you want your db to persist in dev
    #volumes:
    #  - "./data/postgres:/var/lib/postgresql/data"