services:

  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./examples:/app/src/assets/examples
    depends_on:
      - jsonrpc

  jsonrpc:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.rpc
      target: prod
    ports:
      - "${RPCPORT}:${RPCPORT}"
    depends_on:
      - ollama
      - postgres
      - genvm

  webrequest:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.webrequest
    shm_size: 2gb
    volumes:
      - ./webrequest:/app/webrequest
    environment:
      - FLASK_SERVER_PORT=${WEBREQUESTPORT}
    expose:
      - "${WEBREQUESTPORT}"

  genvm:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.genvm
      target: prod
    expose:
      - "${GENVMPORT}"
    command: python genvm/server.py

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./.ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always

  postgres:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.database
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    # If you want your database data to persist
    #volumes:
    #  - "./data/postgres:/var/lib/postgresql/data"
