services:
  traefik:
    profiles: ["studio"]
    image: traefik:v3.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
      target: ${FRONTEND_BUILD_TARGET:-final}
      args:
        - VITE_*
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./examples:/app/src/assets/examples
      - ./frontend/src:/app/src
    depends_on:
      jsonrpc:
        condition: service_healthy
    expose:
      - "${FRONTEND_PORT}"
    environment:
      - VITE_*
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.rule: Host(`${SERVER_NAME}`)
      traefik.http.routers.frontend.entrypoints: websecure
      traefik.http.routers.frontend.tls: true

  jsonrpc:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.backend
      target: ${BACKEND_BUILD_TARGET:-prod}
    environment:
      - FLASK_SERVER_PORT=${RPCPORT}
      # TODO: remove this in production
      - PYTHONUNBUFFERED=1
      - RPCDEBUGPORT=${RPCDEBUGPORT}
      - WEBDRIVERHOST=${WEBDRIVERHOST}
      - WEBDRIVERPORT=${WEBDRIVERPORT}
    ports:
      - "${RPCPORT}:${RPCPORT}"
      - "${RPCDEBUGPORT}:${RPCDEBUGPORT}"
    volumes:
      - ./.env:/app/.env
      - ./backend:/app/backend
      # - hardhat_artifacts:/app/hardhat/artifacts
      # - hardhat_deployments:/app/hardhat/deployments
    depends_on:
      database-migration:
        condition: service_completed_successfully
      webdriver:
        condition: service_healthy
      # hardhat:
      #   condition: service_healthy
      #   required: false
      ollama:
        condition: service_started
        required: false
    expose:
      - "${RPCPORT}"
    healthcheck:
      test: ["CMD", "python3", "backend/healthcheck.py", "--port", "${RPCPORT}"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: ${JSONRPC_REPLICAS:-1}
    labels:
      traefik.enable: true
      traefik.http.routers.jsonrpc.rule: Host(`${SERVER_NAME}`) && (PathPrefix(`/api`) || PathPrefix(`/socket.io`) || PathPrefix(`/ws`) || PathPrefix(`/health`))
      traefik.http.routers.jsonrpc.entrypoints: websecure
      traefik.http.routers.jsonrpc.tls: true

  webdriver:
    image: yeagerai/genlayer-genvm-webdriver:0.0.3
    shm_size: 2gb
    environment:
      - PORT=${WEBDRIVERPORT:-4444}
    expose:
      - "${WEBDRIVERPORT:-4444}"
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ollama:
    profiles: ["ollama"]
    image: ollama/ollama:0.6.5
    ports:
      - 11434:11434
    volumes:
      - ./.ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:16-alpine
    command: sh -c "if [ \"$REMOTE_DATABASE\" = \"true\" ]; then echo 'Postgres disabled in hosted environment' && exec tail -f /dev/null; else exec docker-entrypoint.sh postgres; fi"
    ports:
      - "${DBPORT}:5432"
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
      - REMOTE_DATABASE=${REMOTE_DATABASE}
    healthcheck:
      test: if [ "$REMOTE_DATABASE" = "true" ]; then exit 0; else pg_isready -U ${DBUSER} -d ${DBNAME}; fi
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    security_opt:
      - "no-new-privileges=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Database data - use 'docker compose down -v' to wipe
    volumes:
      - postgres_data:/var/lib/postgresql/data

  database-migration:
    build:
      context: .
      dockerfile: docker/Dockerfile.database-migration
    environment:
      - DB_URL=postgresql://${DBUSER}:${DBPASSWORD}@${DBHOST}:${DBPORT}/${DBNAME}
    depends_on:
      postgres:
        condition: service_healthy
        required: false

  # hardhat:
  #   profiles: ["hardhat"]
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.hardhat
  #   ports:
  #     - "${HARDHAT_PORT:-8545}:8545"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./hardhat:/app/hardhat_src
  #     - hardhat_artifacts:/app/artifacts
  #     - hardhat_cache:/app/cache
  #     - hardhat_deployments:/app/deployments
  #     - hardhat_snapshots:/app/snapshots
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "50m"
  #       max-file: "10"
  #   labels:
  #     traefik.enable: true
  #     traefik.http.routers.hardhat.rule: Host(`${SERVER_NAME}`) && PathPrefix(`/hardhat`)
  #     traefik.http.routers.hardhat.entrypoints: websecure
  #     traefik.http.routers.hardhat.tls: true

  vector:
    profiles: ["studio"]
    image: timberio/vector:0.42.0-alpine
    container_name: vector
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/vector/gcp_credentials.json
      - VECTOR_LOG=info
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./gcp_credentials.json:/etc/vector/gcp_credentials.json:ro
      - /var/log:/var/log:ro  # Mount the host's /var/log directory
    # network_mode: host
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      org.label-schema.group: "monitoring"

volumes:
  # hardhat_artifacts:
  # hardhat_cache:
  # hardhat_deployments:
  ignition_deployments:
  # hardhat_snapshots:
  postgres_data:
