log:
  level: INFO
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# enable dashboard on 8080 with NO AUTH
api:
  dashboard: false

providers:
  docker:
    exposedByDefault: false
