"""add blocked at and worker id to transactions

Revision ID: 96840ab9133a
Revises: 035ef00c2779
Create Date: 2025-09-11 13:18:28.225878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96840ab9133a'
down_revision: Union[str, None] = '035ef00c2779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transactions', sa.Column('worker_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'worker_id')
    op.drop_column('transactions', 'blocked_at')
    # ### end Alembic commands ###
