"""add fees distribution

Revision ID: d30f826417f1
Revises: a221e802477c
Create Date: 2025-07-25 15:19:28.949369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d30f826417f1"
down_revision: Union[str, None] = "a221e802477c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "fees_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "transactions", sa.Column("appeal_count", sa.Integer(), nullable=True)
    )
    op.drop_column("transactions", "config_rotation_rounds")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "config_rotation_rounds", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("transactions", "appeal_count")
    op.drop_column("transactions", "fees_distribution")
    # ### end Alembic commands ###
