# Sometimes this workflow fails due to problems in the target PR branch. I (Agustín Díaz) don't know yet the reason why the code is analyzing for the merge commit instead of the PR branch.
# Anyways, it's an indicator that the target PR branch is not clean. This is a good thing because it helps to keep the codebase clean.
# To fix this, rebase the PR branch with the target branch and check `pre-commit run --all-files` locally.
name: pre-commit

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - run: pip install black
      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
        working-directory: frontend
      # Run pre-commit
      - uses: pre-commit/action@v3.0.1
