name: "Frontend Unit Tests"

on:
  workflow_call:

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - run: npm ci
        working-directory: frontend
      - run: npm run test:unit
        working-directory: frontend

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
