name: Load Test with oha CLI

on:
  push:
    branches:
      - '*'

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Install oha
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
          curl -sSfL https://github.com/hatoo/oha/releases/download/v1.4.5/oha-linux-amd64 -o oha
          chmod +x oha
          sudo mv oha /usr/local/bin

      - name: Run Load Test
        run: ./tests/load/test.sh
