name: Only merge release branches to main

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main
      - staging

jobs:
  validate-pr-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is a release branch
        run: |
          if [[ ${{ github.event.pull_request.base.ref }} == "staging" ]]; then
              echo "Target branch is staging"
              exit 0
          fi
          if [[ ${{ github.event.pull_request.head.ref }} =~ ^release/.*$ ]]; then
              echo "Source branch is a release branch"
              exit 0
          else
              echo "Source branch is not a release branch"
              exit 1
          fi
