name: Changelog
on:
  push:
    branches:
      - 211-sim-ops-generate-pr-from-staging-to-main-with-changelog

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "✏️ Generate release changelog"
        id: changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          unreleasedOnly: true
          unreleasedLabel: "Next release"
          stripGeneratorNotice: true
          issues: false
          # futureRelease:
          releaseBranch: release-0.1.1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "echo changelog"
        run: echo "${{ steps.changelog.outputs.changelog }}"

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6
