name: Changelog
on:
  push:
    branches:
      - 211-sim-ops-generate-pr-from-staging-to-main-with-changelog

jobs:
  release-notes-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release
        id: get_latest_release
        run: |
          latest_release=$(gh release view --json tagName --jq .tagName)
          e
          echo "tag=$latest_release" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate release notes
        id: generate_release_notes
        run: |
          notes=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/yeagerai/genlayer-simulator/releases/generate-notes \
          -d '{"tag_name":"v0.1.1","commitish":"release-0.1.1","previous_tag_name":"v0.1.0"}' \
          )
          echo "notes=$notes" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          branch: release-${{ steps.get_latest_release.outputs.tag }}
          title: Release ${{ steps.get_latest_release.outputs.tag }}
          body: ${{ steps.generate_release_notes.outputs.notes }}
