name: "Unit Tests - PR Approved"

on:
  pull_request_review:
    types:
      - submitted

permissions:
  contents: read

jobs:
  frontend-unit-tests:
    if: (github.event.review.state == 'approved' && github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]')
    name: Unit Tests (Real LLMs)
    uses: ./.github/workflows/frontend-unit-tests.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  backend-unit-tests:
    if: (github.event.review.state == 'approved' && github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]')
    runs-on: ubuntu-latest
    env:
      TEST_WITH_MOCK_LLMS: "false"  # Use real LLMs for approved PRs
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.3
          cache: pip
      - run: pip install -r backend/protocol_rpc/requirements.txt
      - run: pip install pytest-cov
      - run: pytest tests/unit --cov=backend --cov-report=xml --cov-branch
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}