name: "Unit Tests"

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main # so that test reports get uploaded to Codecov and SonarCloud
  workflow_dispatch:

permissions:
  contents: read

jobs:
  frontend-unit-tests:
    if: (github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]')
    name: Unit Tests
    uses: ./.github/workflows/frontend-unit-tests.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  explorer-unit-tests:
    if: (github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]')
    name: Explorer Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: explorer
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci --ignore-scripts
      - run: npm run test:fee-accounting
      - run: npm run lint
      - run: npm run build

  backend-unit-tests:
    if: (github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip
      - run: pip install -r backend/requirements.txt
      - run: pip install pytest-cov pytest-xdist
      - run: pytest tests/unit --cov=backend --cov-report=xml --cov-branch -n auto
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
